#!/usr/bin/perl

###############################################################################
## Copyright (c) 2007-2012 SUSE LINUX Products GmbH, Nuernberg, Germany.
## (c) Copyright [2019] Micro Focus or one of its affiliates.
###############################################################################

use strict;
use warnings;
use SMT::CLI;
use SMT::Utils;
use File::Basename;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

if(!SMT::Utils::dropPrivileges())
{
    print STDERR _("Unable to drop privileges. Abort!\n");
    exit 1;
}

sub help
{
    print __("show help\n");
    opendir(DIR, "/usr/sbin") || die "can't opendir '/usr/sbin': $!";
    my @files = grep { /^smt-.+/ && -x "/usr/sbin/$_" } readdir(DIR);
    closedir DIR;

    print __("Subscription Management Tool (SMT). (c)2007-2015 SUSE LINUX Products GmbH, Nuernberg, Germany.\n\n");
    print __("Micro Focus Subscription Management Tool (SMT). (c)2019 Micro Focus or one of its Affiliates.\n\n");

    foreach my $cmd (@files)
    {
        $cmd =~ s/smt\-(.+)/$1/;

        print basename($0) . " $cmd\n";
    }

    print __("\nUse smt help <command> for more help\n");
    exit 0;
}

sub executeCommand
{
  my $name = shift;
  my @options = @_;

  my $exec = "/usr/sbin/smt-$name";
  my $cmd = "$exec ";

  # quote all the options, otherwise whithespace causes problems
  foreach (@options)
  {
    $_ =~ s/\'/\\\'/;
    $cmd .= "'$_' ";
  }

  #print "execute '$cmd'\n";
  if ( -e $exec )
  {
      system($cmd);
  }
  else
  {
    die "$cmd command not installed\n";
  }
}

if (defined $ARGV[0] )
{
    my $cmd = shift(@ARGV);
    #print "cmd: $cmd\n";
    if ( $cmd eq "help" || $cmd eq "-h" || $cmd eq "--help")
    {
        if (defined $ARGV[0] )
        {
            my $targethelp = shift(@ARGV);
            executeCommand($targethelp,"-h");
        }
        else
        {
            help();
        }
    }
    elsif($cmd eq "ncc-scc-migration")
    {
        die "smt ncc-scc-migration requires root privilege. Please execute it directly at /usr/sbin/smt-ncc-scc-migration.\n";
    }
    elsif($cmd eq "scc-ncc-migration")
    {
        die "smt scc-ncc-migration requires root privilege. Please execute it directly at /usr/sbin/smt-scc-ncc-migration.\n";
    }
    else
    {
        executeCommand($cmd, @ARGV)
    }
}
else
{
    help();
}

exit 0;

#
# Manpage
#


=head1 NAME

smt - "Subscription Management Tool" for SLE Maintenance

=head1 SYNOPSIS

smt [help|--help|-h] <subcommand> [options]

=head1 DESCRIPTION

smt calls various subcommands to administrate your SMT Server.


=head1 OPTIONS

=head2 help --help -h

If this option is used without subcommand, it shows the list of available subcommands.
If this option is used with a subcommand, it shows the help text of the subcommand.

=head1 AUTHORS and CONTRIBUTORS

Duncan Mac-Vicar Prett, Lukas Ocilka, Jens Daniel Schmidt, Michael Calmer

=head1 LICENSE

Copyright (c) 2007-2012 SUSE LINUX Products GmbH, Nuernberg, Germany.
(c) Copyright [2019] Micro Focus or one of its affiliates.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 675 Mass
Ave, Cambridge, MA 02139, USA.

Licensed under the GPLv2 License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:(https://opensource.org/licenses/GPL-2.0)

Unless required by applicable law or agreed to in writing, software distributed 
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations 
under the License.

=cut

