#!/usr/bin/perl

###############################################################################
## Copyright (c) 2014 SUSE LINUX Products GmbH, Nuernberg, Germany.
## (c) Copyright [2019] Micro Focus or one of its affiliates.
###############################################################################

use strict;
use warnings;
use SMT::Utils;

use Locale::gettext ();
use POSIX ();     # Needed for setlocale()

POSIX::setlocale(&POSIX::LC_MESSAGES, "");

my $exec = "/usr/sbin/smt-scc-sync";
my $cfg = undef;
eval
{
    $cfg = SMT::Utils::getSMTConfig();
};
if($@ || !defined $cfg)
{
    print sprintf(__("Cannot read the SMT configuration file: %s"), $@);
    exit 1;
}

if ( $cfg->val('NU', 'ApiType', 'NCC') eq 'NCC')
{
    $exec = "/usr/sbin/smt-ncc-sync";
}

sub executeCommand
{
  my $command = shift;
  my @options = @_;

  my $cmd = "$command ";

  # quote all the options, otherwise whithespace causes problems
  foreach (@options)
  {
    $_ =~ s/\'/\\\'/;
    $cmd .= "'$_' ";
  }

  #print "execute '$cmd'\n";
  if ( ! -e $command )
  {
    die "$cmd command not installed\n";
  }
  return system($cmd);
}

my $ret = executeCommand($exec, @ARGV);
exit $ret;

#
# Manpage
#

=head1 NAME

smt-sync - sync from customer center

=head1 SYNOPSIS

smt-sync [--help|-h] [options]

=head1 DESCRIPTION

Wrapper for smt-ncc-sync or smt-scc-sync depending on the configuration.


=head1 AUTHORS and CONTRIBUTORS

Duncan Mac-Vicar Prett, Lukas Ocilka, Jens Daniel Schmidt, Michael Calmer

=head1 LICENSE

Copyright (c) 2014 SUSE LINUX Products GmbH, Nuernberg, Germany.
(c) Copyright [2019] Micro Focus or one of its affiliates.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 675 Mass
Ave, Cambridge, MA 02139, USA.

Licensed under the GPLv2 License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:(https://opensource.org/licenses/GPL-2.0)

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations
under the License.

=cut

